FROM postgres:15

# Configurar locales correctamente
RUN apt-get update && apt-get install -y locales \
    && sed -i '/es_AR.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen \
    && export LANG=es_AR.UTF-8 \
    && update-locale LANG=es_AR.UTF-8 LC_ALL=es_AR.UTF-8
