[options]
; Configuración de la base de datos
db_host = db  ; Si estás usando Docker, la base de datos debe ser el servicio llamado "db" (o lo que hayas configurado en docker-compose)
db_port = 5432
db_user = odoo  ; El usuario que configuraste para PostgreSQL
db_password = SuperSecret123!  ; La contraseña que configuraste para PostgreSQL
db_name = False  ; Odoo generalmente no necesita un nombre de base de datos aquí, ya que puede usar la que se especifique en el momento de la conexión

; Configuración de la red y el acceso
proxy_mode = True
log_level = info
log_file = /var/log/odoo/odoo.log

; Otros valores por defecto
addons_path = /opt/odoo/addons
admin_passwd = Odoo913!  ; Cambia esto por tu contraseña de administrador

; Redefinir el puerto en caso de necesitarlo
http_port = 8069
